
// Comprehensive list of 5-letter English words
const WORD_LIST = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alien', 'align', 'alike', 'alive',
  'allow', 'alone', 'along', 'alter', 'amber', 'among', 'anger', 'angle', 'angry', 'apart',
  'apple', 'apply', 'arena', 'argue', 'arise', 'armed', 'armor', 'array', 'arrow', 'aside',
  'asset', 'atlas', 'audio', 'audit', 'avoid', 'awake', 'award', 'aware', 'badly', 'basic',
  'batch', 'beach', 'began', 'begin', 'being', 'below', 'bench', 'billy', 'birth', 'black',
  'blame', 'blank', 'blast', 'blind', 'block', 'blood', 'blown', 'blues', 'board', 'boost',
  'booth', 'bound', 'brain', 'brand', 'brass', 'brave', 'bread', 'break', 'breed', 'brief',
  'bring', 'broad', 'broke', 'brown', 'build', 'built', 'buyer', 'cable', 'carry', 'catch',
  'cause', 'chain', 'chair', 'chaos', 'charm', 'chart', 'chase', 'cheap', 'check', 'chest',
  'chief', 'child', 'china', 'chose', 'civic', 'civil', 'claim', 'class', 'clean', 'clear',
  'click', 'climb', 'clock', 'close', 'cloud', 'coach', 'coast', 'could', 'count', 'court',
  'cover', 'craft', 'crash', 'crazy', 'cream', 'crime', 'cross', 'crowd', 'crown', 'crude',
  'curve', 'cycle', 'daily', 'dance', 'dated', 'dealt', 'death', 'debut', 'delay', 'depth',
  'doing', 'doubt', 'dozen', 'draft', 'drama', 'drank', 'dream', 'dress', 'drill', 'drink',
  'drive', 'drove', 'dying', 'eager', 'early', 'earth', 'eight', 'elite', 'empty', 'enemy',
  'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra',
  'faith', 'false', 'fault', 'fiber', 'field', 'fifth', 'fifty', 'fight', 'final', 'first',
  'fixed', 'flash', 'fleet', 'floor', 'fluid', 'focus', 'force', 'forth', 'forty', 'forum',
  'found', 'frame', 'frank', 'fraud', 'fresh', 'front', 'fruit', 'fully', 'funny', 'giant',
  'given', 'glass', 'globe', 'going', 'grace', 'grade', 'grand', 'grant', 'grass', 'grave',
  'great', 'green', 'gross', 'group', 'grown', 'guard', 'guess', 'guest', 'guide', 'happy',
  'harry', 'heart', 'heavy', 'hence', 'henry', 'horse', 'hotel', 'house', 'human', 'ideal',
  'image', 'index', 'inner', 'input', 'issue', 'japan', 'jimmy', 'joint', 'jones', 'judge',
  'known', 'label', 'large', 'laser', 'later', 'laugh', 'layer', 'learn', 'lease', 'least',
  'leave', 'legal', 'level', 'lewis', 'light', 'limit', 'links', 'lives', 'local', 'loose',
  'lower', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker', 'march', 'maria', 'match',
  'maybe', 'mayor', 'meant', 'media', 'metal', 'might', 'minor', 'minus', 'mixed', 'model',
  'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'moved', 'movie', 'music',
  'needs', 'never', 'newly', 'night', 'noise', 'north', 'noted', 'novel', 'nurse', 'occur',
  'ocean', 'offer', 'often', 'order', 'other', 'ought', 'paint', 'panel', 'paper', 'party',
  'peace', 'peter', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pitch', 'place',
  'plain', 'plane', 'plant', 'plate', 'point', 'pound', 'power', 'press', 'price', 'pride',
  'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove', 'queen', 'quick', 'quiet',
  'quite', 'radio', 'raise', 'range', 'rapid', 'ratio', 'reach', 'ready', 'realm', 'rebel',
  'refer', 'relax', 'renew', 'reply', 'right', 'rigid', 'rival', 'river', 'robin', 'roger',
  'roman', 'rough', 'round', 'route', 'royal', 'rural', 'scale', 'scene', 'scope', 'score',
  'sense', 'serve', 'setup', 'seven', 'shall', 'shape', 'share', 'sharp', 'sheet', 'shelf',
  'shell', 'shift', 'shine', 'shirt', 'shock', 'shoot', 'short', 'shown', 'sight', 'simon',
  'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide', 'small', 'smart', 'smile', 'smith',
  'smoke', 'snake', 'solid', 'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'speak',
  'speed', 'spend', 'spent', 'split', 'spoke', 'sport', 'staff', 'stage', 'stake', 'stand',
  'start', 'state', 'steam', 'steel', 'steep', 'steer', 'steve', 'stick', 'still', 'stock',
  'stone', 'stood', 'store', 'storm', 'story', 'strip', 'stuck', 'study', 'stuff', 'style',
  'sugar', 'suite', 'super', 'sweet', 'table', 'taken', 'taste', 'taxes', 'teach', 'teams',
  'terry', 'texas', 'thank', 'theft', 'their', 'theme', 'there', 'these', 'thick', 'thing',
  'think', 'third', 'those', 'three', 'threw', 'throw', 'thumb', 'tiger', 'tight', 'times',
  'tired', 'title', 'today', 'token', 'topic', 'total', 'touch', 'tough', 'tower', 'track',
  'trade', 'train', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried', 'tries', 'truck',
  'truly', 'trunk', 'trust', 'truth', 'twice', 'twist', 'typed', 'uncle', 'under', 'undue',
  'union', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'valid', 'value',
  'video', 'virus', 'visit', 'vital', 'vocal', 'voice', 'waste', 'watch', 'water', 'wheel',
  'where', 'which', 'while', 'white', 'whole', 'whose', 'woman', 'women', 'world', 'worry',
  'worse', 'worst', 'worth', 'would', 'write', 'wrong', 'wrote', 'young', 'youth',
  // Additional common 5-letter words
  'pizza', 'table', 'chair', 'house', 'mouse', 'phone', 'plate', 'knife', 'spoon', 'bread',
  'water', 'juice', 'dance', 'music', 'movie', 'books', 'games', 'sport', 'beach', 'party',
  'smile', 'laugh', 'happy', 'sunny', 'windy', 'rainy', 'snowy', 'cloud', 'storm', 'peace',
  'quiet', 'noise', 'sound', 'touch', 'smell', 'taste', 'sight', 'heart', 'brain', 'hands',
  'trees', 'grass', 'plant', 'river', 'beach', 'hills', 'roads', 'towns', 'cities', 'homes',
  'doors', 'walls', 'floor', 'rooms', 'light', 'night', 'sleep', 'dream', 'awake', 'tired',
  'funny', 'silly', 'crazy', 'weird', 'smart', 'brave', 'strong', 'quick', 'slow', 'fast',
  'small', 'large', 'tiny', 'huge', 'short', 'tall', 'wide', 'thin', 'thick', 'heavy',
  'fresh', 'clean', 'dirty', 'messy', 'neat', 'fancy', 'plain', 'cheap', 'fancy', 'rich',
  'words', 'spell', 'typed', 'wrote', 'notes', 'lists', 'plans', 'ideas', 'think', 'learn'
];

// Common dictionary words for validation (more permissive)
const VALID_WORDS = new Set([
  ...WORD_LIST,
  // Add more common English words that might not be in the answer list
  'abuse', 'acids', 'acres', 'acted', 'added', 'adult', 'afire', 'aging', 'aimed', 'alarm',
  'amber', 'among', 'angel', 'angry', 'ankle', 'apple', 'areas', 'armed', 'array', 'asked',
  'atlas', 'atoms', 'awake', 'badge', 'badly', 'bagel', 'baker', 'balls', 'bands', 'banks',
  'based', 'basic', 'batch', 'beach', 'beans', 'beard', 'bears', 'beast', 'began', 'being',
  'belly', 'below', 'bench', 'bikes', 'bills', 'birds', 'birth', 'blade', 'blame', 'blank',
  'blast', 'blaze', 'bleed', 'blend', 'bless', 'blind', 'block', 'blood', 'bloom', 'blown',
  'blues', 'board', 'boats', 'bones', 'booth', 'boots', 'bound', 'bowls', 'boxes', 'brain',
  'brake', 'brand', 'brass', 'brave', 'bread', 'break', 'breed', 'brick', 'bride', 'brief',
  'bring', 'broad', 'broke', 'brook', 'brown', 'brush', 'build', 'built', 'bunch', 'burst',
  'buses', 'buyer', 'cable', 'cabin', 'cakes', 'calls', 'camps', 'canal', 'candy', 'cards',
  'carry', 'cases', 'catch', 'cause', 'caves', 'chain', 'chair', 'chaos', 'charm', 'chart',
  'chase', 'cheap', 'check', 'chess', 'chest', 'child', 'china', 'chips', 'chose', 'civic',
  'civil', 'claim', 'class', 'clean', 'clear', 'click', 'climb', 'clock', 'close', 'cloth',
  'cloud', 'clubs', 'coach', 'coast', 'codes', 'coins', 'color', 'comet', 'coral', 'cores',
  'costs', 'couch', 'could', 'count', 'court', 'cover', 'craft', 'crane', 'crash', 'crazy',
  'cream', 'crime', 'cross', 'crowd', 'crown', 'crude', 'crush', 'curve', 'cycle', 'daily',
  'dairy', 'dance', 'dates', 'dealt', 'death', 'debut', 'decks', 'delay', 'dense', 'depth',
  'desks', 'devil', 'diary', 'diced', 'dimes', 'diner', 'ditch', 'diets', 'dirty', 'disco',
  'docks', 'doing', 'doors', 'doubt', 'dozen', 'draft', 'drain', 'drama', 'drank', 'drawn',
  'dream', 'dress', 'drill', 'drink', 'drive', 'drove', 'drums', 'ducks', 'dying', 'eager',
  'early', 'earth', 'eight', 'elect', 'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry',
  'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra', 'faced', 'facts', 'faith',
  'false', 'fancy', 'farms', 'fatal', 'fault', 'feast', 'fever', 'fiber', 'field', 'fifth',
  'fifty', 'fight', 'files', 'films', 'final', 'finds', 'fines', 'fired', 'first', 'fixed',
  'flags', 'flame', 'flash', 'fleet', 'flesh', 'flies', 'float', 'flood', 'floor', 'flour',
  'flows', 'fluid', 'focus', 'folks', 'fonts', 'foods', 'force', 'forms', 'forth', 'forty',
  'forum', 'found', 'frame', 'frank', 'fraud', 'fresh', 'front', 'frost', 'fruit', 'fully',
  'funds', 'funny', 'games', 'gates', 'ghost', 'giant', 'gifts', 'girls', 'given', 'glass',
  'globe', 'glory', 'glove', 'goals', 'going', 'goods', 'grace', 'grade', 'grain', 'grand',
  'grant', 'grape', 'graph', 'grass', 'grave', 'great', 'greek', 'green', 'greet', 'grief',
  'grill', 'gross', 'group', 'grown', 'grows', 'guard', 'guess', 'guest', 'guide', 'guilt',
  'habit', 'hands', 'happy', 'harsh', 'haste', 'hated', 'heads', 'heard', 'heart', 'heavy',
  'hence', 'herbs', 'hills', 'hints', 'hired', 'hobby', 'holds', 'holes', 'honey', 'hooks',
  'hoped', 'horse', 'hotel', 'house', 'human', 'humor', 'hurry', 'ideal', 'ideas', 'image',
  'index', 'inner', 'input', 'items', 'ivory', 'jewel', 'joins', 'jokes', 'judge', 'juice',
  'jumps', 'keeps', 'kinds', 'kings', 'knife', 'known', 'label', 'labor', 'lacks', 'lakes',
  'lands', 'large', 'laser', 'later', 'laugh', 'layer', 'leads', 'learn', 'lease', 'least',
  'leave', 'legal', 'lemon', 'level', 'light', 'liked', 'limit', 'lined', 'links', 'lions',
  'lists', 'lived', 'liver', 'lives', 'loads', 'loans', 'lobby', 'local', 'locks', 'logic',
  'looks', 'loose', 'loved', 'lower', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker',
  'males', 'march', 'marks', 'match', 'maybe', 'mayor', 'meals', 'means', 'meant', 'medal',
  'media', 'meets', 'melon', 'memory', 'metal', 'meter', 'might', 'minds', 'mines', 'minor',
  'minus', 'mixed', 'model', 'modes', 'money', 'month', 'moral', 'motor', 'mount', 'mouse',
  'mouth', 'moved', 'moves', 'movie', 'music', 'naked', 'named', 'names', 'nancy', 'needs',
  'never', 'newly', 'night', 'noise', 'north', 'noted', 'notes', 'novel', 'nurse', 'ocean',
  'offer', 'often', 'older', 'olive', 'opens', 'opera', 'order', 'organ', 'other', 'ought',
  'owned', 'owner', 'pages', 'paint', 'pairs', 'panel', 'paper', 'parks', 'parts', 'party',
  'paste', 'patch', 'paths', 'pause', 'peace', 'peaks', 'penny', 'phase', 'phone', 'photo',
  'piano', 'picks', 'piece', 'pills', 'pilot', 'pitch', 'pizza', 'place', 'plain', 'plane',
  'plant', 'plate', 'plays', 'plaza', 'poems', 'point', 'polls', 'pools', 'pound', 'power',
  'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove',
  'pulls', 'pumps', 'punch', 'queen', 'query', 'quest', 'quick', 'quiet', 'quite', 'quote',
  'radio', 'raise', 'range', 'rapid', 'rates', 'ratio', 'reach', 'reads', 'ready', 'realm',
  'rebel', 'refer', 'relax', 'renew', 'reply', 'rides', 'ridge', 'right', 'rigid', 'rings',
  'rises', 'risks', 'rival', 'river', 'roads', 'robot', 'roles', 'roman', 'rooms', 'roots',
  'roses', 'rough', 'round', 'route', 'royal', 'rugby', 'rules', 'rural', 'safer', 'saint',
  'salad', 'sales', 'sandy', 'sauce', 'saved', 'scale', 'scary', 'scene', 'scope', 'score',
  'seats', 'seems', 'sells', 'sense', 'serve', 'setup', 'seven', 'shade', 'shake', 'shall',
  'shame', 'shape', 'share', 'sharp', 'sheep', 'sheet', 'shelf', 'shell', 'shift', 'shine',
  'ships', 'shirt', 'shock', 'shoes', 'shoot', 'shops', 'shore', 'short', 'shots', 'shown',
  'shows', 'sides', 'sight', 'signs', 'silly', 'since', 'sinks', 'sites', 'sixth', 'sixty',
  'sized', 'sizes', 'skill', 'sleep', 'slide', 'slope', 'small', 'smart', 'smile', 'smoke',
  'snake', 'snow', 'solid', 'solve', 'songs', 'sorry', 'sorts', 'souls', 'sound', 'south',
  'space', 'spare', 'speak', 'speed', 'spend', 'spent', 'spite', 'split', 'spoke', 'sport',
  'staff', 'stage', 'stake', 'stamp', 'stand', 'stars', 'start', 'state', 'stays', 'steam',
  'steel', 'steep', 'steps', 'stick', 'still', 'stock', 'stone', 'stood', 'stops', 'store',
  'storm', 'story', 'strip', 'stuck', 'study', 'stuff', 'style', 'sugar', 'suite', 'sunny',
  'super', 'sweet', 'swift', 'swing', 'swiss', 'table', 'takes', 'talks', 'tanks', 'tapes',
  'tasks', 'taste', 'taxes', 'teach', 'teams', 'tears', 'tells', 'terms', 'tests', 'texas',
  'thank', 'theft', 'their', 'theme', 'there', 'these', 'thick', 'thing', 'think', 'third',
  'those', 'three', 'threw', 'throw', 'thumb', 'tiger', 'tight', 'tiles', 'times', 'tired',
  'title', 'today', 'token', 'tools', 'topic', 'total', 'touch', 'tough', 'tours', 'tower',
  'towns', 'track', 'trade', 'trail', 'train', 'trans', 'trash', 'treat', 'trees', 'trend',
  'trial', 'tribe', 'trick', 'tried', 'tries', 'trips', 'truck', 'truly', 'trunk', 'trust',
  'truth', 'tubes', 'turns', 'twice', 'twist', 'typed', 'types', 'uncle', 'under', 'union',
  'unity', 'until', 'upper', 'upset', 'urban', 'urged', 'usage', 'users', 'usual', 'valid',
  'value', 'video', 'views', 'virus', 'visit', 'vital', 'vocal', 'voice', 'votes', 'wages',
  'walks', 'walls', 'wants', 'waste', 'watch', 'water', 'waves', 'weeks', 'wheel', 'where',
  'which', 'while', 'white', 'whole', 'whose', 'width', 'wines', 'wings', 'wired', 'woman',
  'women', 'woods', 'words', 'works', 'world', 'worry', 'worse', 'worst', 'worth', 'would',
  'write', 'wrong', 'wrote', 'yards', 'years', 'young', 'yours', 'youth', 'zones'
]);

export const getRandomWord = (): string => {
  return WORD_LIST[Math.floor(Math.random() * WORD_LIST.length)];
};

export const isValidWord = (word: string): boolean => {
  return VALID_WORDS.has(word.toLowerCase());
};
